name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md

  pull_request:
    branches: ["main"]
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          # platforms: linux/amd64, linux/arm64
          push: true
          tags: howxcheng/nginx-with-http3:latest
          # cache-from: type=gha,scope=nginx-with-http3
          # cache-to: type=gha,mode=max,scope=nginx-with-http3
